name: Telegram Views AutoRun

on:
  schedule:
    - cron: "0 */6 * * *"  # Автозапуск каждые 6 часов (время UTC)
  workflow_dispatch:       # Возможность запустить вручную

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: |
          python main.py --mode auto --channel @epitaphia_bio --post 47
